### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by karanchawla** [ztalbot2000/crosstool-arm-osx#10] opened 2018-05-25 20:50 UTC
Tried running the shell script on Mac OS Sierra 10.12.16 and got the following error

```
Compiling crosstool-ng... in /Volumes/CrossToolNG/crosstool-ng-src
/usr/bin/make  all-recursive
Making all in kconfig
/usr/bin/make  all-am
depbase=`echo conf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -DHAVE_CONFIG_H -I. -I..  -include config.h -DCONFIG_=\"CT_\"   -g -O2 -MT conf.o -MD -MP -MF $depbase.Tpo -c -o conf.o conf.c &&\
	mv -f $depbase.Tpo $depbase.Po
In file included from conf.c:19:
./lkc.h:12:11: fatal error: 'libintl.h' file not found
# include <libintl.h>
          ^~~~~~~~~~~
1 error generated.
make[3]: *** [conf.o] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

After searching a little on the web, some users suggested installing gettext, so I added that in BrewTools in the bash script but that didn't solve the problem either.

Am I missing something obvious?

**Comment by ztalbot2000** [comment] 2018-06-01 18:10
I haven't had to use the tool in a while.  It does compile crosstool-ng latest and it seems they busted something as I have just reproduced your problem.  I'll try and figure out what they did and update this tool afterwards

**Comment by ztalbot2000** [comment] 2018-06-03 15:00
OSX seems to have a long history of problems with lib
Intl.h.  This is now fixed and ct-nt compiles.
There my still be an issue with the config file provided as it seems to be ot of date with the latest crosstool-ng.  I will look at that as a separate issue or you could try your own using ct-nt menuconfig

**Comment by ztalbot2000** [comment] 2018-06-03 15:00
Done

**Closed by ztalbot2000** 2018-06-03 15:00 UTC

**Comment by ztalbot2000** [comment] 2018-06-04 06:41
I just want to note that I was now successful in building the cross compiler

**Comment by karanchawla** [comment] 2018-06-04 17:30
Great, thanks! I'll try to compile it sometime this evening.
